blacklist: []
build_space: build_limo_release
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
- -DCMAKE_CXX_FLAGS=-Wall
- -Wextra
- -Wno-unused-parameter
- -Werror=address
- -Werror=array-bounds=1
- -Werror=bool-compare
- -Werror=comment
- -Werror=enum-compare
- -Werror=format
- -Werror=init-self
- -Werror=logical-not-parentheses
- -Werror=maybe-uninitialized
- -Werror=memset-transposed-args
- -Werror=nonnull
- -Werror=nonnull-compare
- -Werror=openmp-simd
- -Werror=parentheses
- -Werror=return-type
- -Werror=sequence-point
- -Werror=sizeof-pointer-memaccess
- -Werror=switch
- -Werror=tautological-compare
- -Werror=trigraphs
- -Werror=uninitialized
- -Werror=volatile-register-var
devel_layout: linked
devel_space: devel_limo_release
extend_path: null
install: false
install_space: install_limo_release
isolate_install: false
jobs_args: []
log_space: logs_limo_release
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
